### ISSUE TITLE
mac 运行出错

### ISSUE THREAD

**Issue by mamingsuper** [jianchang512/stt#15]
感谢开发软件，运行时出现错误，我是mac:
python  start.py
/Users/mam94/Documents/A/To_code/audiotext/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "/Users/mam94/Documents/A/To_code/audiotext/stt/start.py", line 13, in <module>
    from stslib import cfg, tool
  File "/Users/mam94/Documents/A/To_code/audiotext/stt/stslib/cfg.py", line 40, in <module>
    sets=parse_ini()
  File "/Users/mam94/Documents/A/To_code/audiotext/stt/stslib/cfg.py", line 11, in parse_ini
    "lang":"en" if locale.getdefaultlocale()[0].split('_')[0].lower() != 'zh' else "zh",
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by jianchang512** [comment]
/Users/mam94/Documents/A/To_code/audiotext/stt/stslib/cfg.py

第11行，改为

"lang":"zh",
