### ISSUE TITLE
locale.getdefaultlocale Error in cfg.py

### ISSUE THREAD

**Issue by pyvadev** [jianchang512/stt#26]
### Env
version: 0.92
platform: Mac Air M1

pull project as README and run, then throw error as follow:
```
Traceback (most recent call last):
  File ".../stt/start.py", line 13, in <module>
    from stslib import cfg, tool
  File ".../stt/stslib/cfg.py", line 41, in <module>
    sets=parse_ini()
  File ".../stt/stslib/cfg.py", line 11, in parse_ini
    "lang":"en" if locale.getdefaultlocale()[0].split('_')[0].lower() != 'zh' else "zh", 
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by jianchang512** [comment]
../stt/stslib/cfg.py 
line 11



  "lang":"en" if locale.getdefaultlocale()[0].split('_')[0].lower() != 'zh' else "zh",


edit to 

"lang":"en"
