### ISSUE TITLE
使用预编译Win版时，出现ERROR in start: [upload]error: [WinError 2] 系统找不到指定的文件。错误

### ISSUE THREAD

**Issue by blbl147** [jianchang512/stt#64]
使用预编译Win版时，出现ERROR in start: [upload]error: [WinError 2] 系统找不到指定的文件。错误
![1](https://github.com/user-attachments/assets/67c286c3-ba38-4c21-9baa-7dd476e49056)

**Comment by jianchang512** [comment]
出错信息太少，看不出来

出错时 sts.log 下最后几行记录复制。

**Comment by jianchang512** [comment]
无法复现该错误

出错时上传的什么文件，完整路径是什么，是否存在空格、中文等特殊符号，如果有，尝试去掉重试。

cmd窗口截大图看完整信息

sts.log 文件最后10行完整复制粘贴

**Comment by Carzer** [comment]
我也遇到了相同的问题

~~~
2024-07-16 15:43:02,168 - start - ERROR - Exception on /process [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1455, in wsgi_app
  File "flask\app.py", line 869, in full_dispatch_request
  File "flask\app.py", line 867, in full_dispatch_request
  File "flask\app.py", line 852, in dispatch_request
  File "start.py", line 149, in process
AttributeError: 'NoneType' object has no attribute 'strip'
2024-07-16 15:52:29,443 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
2024-07-16 15:52:39,787 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
2024-07-16 15:53:15,162 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
2024-07-16 15:57:11,433 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
2024-07-16 15:59:44,120 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
2024-07-16 16:05:37,998 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
2024-07-16 16:05:42,051 - start - ERROR - Exception on /process [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1455, in wsgi_app
  File "flask\app.py", line 869, in full_dispatch_request
  File "flask\app.py", line 867, in full_dispatch_request
  File "flask\app.py", line 852, in dispatch_request
  File "start.py", line 149, in process
AttributeError: 'NoneType' object has no attribute 'strip'
2024-07-17 12:40:26,709 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
2024-07-17 12:40:31,461 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
2024-07-17 12:41:25,160 - start - ERROR - [upload]error: [WinError 2] 系统找不到指定的文件。
~~~

**Comment by jianchang512** [comment]
上传时就出错了，上传的文件完整名称是什么，包括盘符和路径。看看软件目录下有没有 static/tmp 文件夹

**Comment by jianchang512** [comment]
右键使用管理员权限打开试试

**Comment by Carzer** [comment]
完整名称：`D:\1.mp4`，其他盘符也尝试过了，软件和视频文件都放在根目录。

`static/tmp`路径下有文件，上传应该是成功了的。

右键管理员也尝试过了，常见的软件测试方案基本都试了一遍，问题依旧。

另外，0.91是正常的，也下载了模型正常使用了，管理员账号和邮箱账号都尝试过了，windows版本：
> 版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎5/‎20
操作系统版本	22631.3880
体验	Windows Feature Experience Pack 1000.22700.1020.0

暂无其他信息提供了。

**Comment by jianchang512** [comment]
static/tmp下有没有 1.wav和1.mp4这2个问卷

**Comment by Carzer** [comment]
> static/tmp下有没有 1.wav和1.mp4这2个问卷

只有mp4，没有wav

**Comment by jianchang512** [comment]
文件夹地址栏输入cmd  ，然后执行 `ffmpeg` 看看输出什么

**Comment by jianchang512** [comment]
软件路径下是否有 ffmpeg.exe 文件

**Comment by Carzer** [comment]
> 文件夹地址栏输入cmd ，然后执行 `ffmpeg` 看看输出什么

我回答完wav以后，也意识到，可能是ffmpeg出问题了，进入文件夹，发现0.91版本里面有ffmpeg，0.93版本没有，复制进去之后，可以正常使用了。

**Comment by jianchang512** [comment]
如果有旧版，只下载补丁包覆盖0.91就行

**Comment by jianchang512** [comment]
如果你的计算机上没有ffmpeg，请下载这2个exe文件，和 start.exe放在同一位置

https://github.com/jianchang512/stt/releases/download/v0.93/ffmpeg.exe

https://github.com/jianchang512/stt/releases/download/v0.93/ffprobe.exe
