### ISSUE TITLE
终端重复报错

### ISSUE THREAD

**Issue by EternityXuNuo** [jianchang512/stt#89]
卡94%,然后后台一直弹如下报错
```
[2024-10-14 13:44:51,265] ERROR in app: Exception on /progressbar [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1455, in wsgi_app
  File "flask\app.py", line 869, in full_dispatch_request
  File "flask\app.py", line 867, in full_dispatch_request
  File "flask\app.py", line 852, in dispatch_request
  File "start.py", line 219, in progressbar
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by jianchang512** [comment]
更新到 0.0.97

**Comment by Bella0818** [comment]
> > 请问您解决了吗？如何解决呢？
> 
> 更新到最新版

好嘞，感谢～
